### ISSUE TITLE
Self hosted API route

### ISSUE THREAD

**Issue by jondashkyle** [sammdec/nfte#21]
First off, huge work so far. This is great.

It could be useful to have an example in the documentation on how to self-host the Next API route. For instance, if it could be possible to import it into an API route within my Next build, and update a prop or environment variable so it uses my endpoint instead of the `nfte.app` endpoint?

**Comment by sammdec** [comment]
I see this as possibly having two parts to it, one would be to package up the core part of the api logic to allow for importing it from a package and using it as a handler. The other part would be to update the react component to support taking in another endpoint url. Does that sound like something that would work for you?

**Comment by jondashkyle** [comment]
Yes! Both of those would be fantastic.

**Comment by sammdec** [comment]
Resolved with #19

**Comment by jondashkyle** [comment]
Looks perfect, using it in a feature branch now :)

**Comment by sammdec** [comment]
Oh thats amazing to hear will be rolling out the updates to nfte.app any minute now
