### ISSUE TITLE
Cannot Retrieve NFT Data

### ISSUE THREAD

**Issue by teashophouse** [sammdec/nfte#25]
When using the NFTE React component, started getting some {error: "Cannot retrieve nft data"} this afternoon. 

Not sure if I misconfigured something, of if your https://nfte.app/api is overloaded at the moment

**Comment by sammdec** [comment]
Do you have the contract and tokenId to hand?

**Comment by nickbytes** [comment]
Getting same error for:

contract=0x60f80121c31a0d46b5279700f9df786054aa5ee5
tokenId=335911

**Comment by sammdec** [comment]
@nickbytes is it a erc-721 token?

**Comment by nickbytes** [comment]
> @nickbytes is it a erc-721 token?

Yes, this is an ERC721 created on rarible.

**Comment by sammdec** [comment]
Do you have the link?

**Comment by nickbytes** [comment]
https://rarible.com/token/0x60f80121c31a0d46b5279700f9df786054aa5ee5:335911

**Comment by sammdec** [comment]
Cool I’ll take a look

**Comment by nickbytes** [comment]
Guessing something on Rarible's end changed. Haven't had a chance to pull down to try to debug, but I have a feeling that media urls changed...

Looks like everything is at `rarible.com` now, whereas before... I thought it was at `app.rarible.com` as [evidenced here ](https://github.com/contextart/nfte/blob/main/packages/handler/src/knownContracts/rarible.js#L50). I could be totally off base here though.

**Comment by sammdec** [comment]
This should now be resolved and deployed to production
